project_id = "ijwwnaqprojdczfppxkf"

# Make admin edge functions callable from the web app without a Supabase JWT
# These functions already validate using service role and internal tokens
[functions.admin-logout]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-session]
verify_jwt = false

[functions.admin-tools]
verify_jwt = false
