// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijwwnaqprojdczfppxkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqd3duYXFwcm9qZGN6ZnBweGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzgyNTcsImV4cCI6MjA1OTg1NDI1N30.Zu3RZXLSz1csaq3uUoKCmGb32MZKYSrourTqg4WNT-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);